// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xruwmyxulgqjcyiwzwis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhydXdteXh1bGdxamN5aXd6d2lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDk0MjIsImV4cCI6MjA3MDU4NTQyMn0.8lOGxIjYs1I6teMIejX-bRDX6_CRi3BqvsovH1Dum_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});